In [8]:
#Alexandra Feely Quiz 1

#1)
import numpy as np

def func(num1, num2, num3):
    if(num1<num2< num3 or num3<num2<num1):
        return num2
    if(num2<num1< num3 or num3<num1< num2):
        return num1
    else:
        return num3
       
func(45,22,60)

#This code takes in three values and finds the median

45

In [47]:
#2)
A = [[1,2,3], [4,5,6], [4,5,2]]
B = [[2,8,6], [5,7,3], [7,8,9]]
C = []
for j in range(0,len(A)):
    C.append([])
    for x in range(0,len(A[j])):
        C[j].append(B[j][x]-A[j][x])
print(C)
Answer = C

[[1, 6, 3], [1, 2, -3], [3, 3, 7]]


In [69]:
import numpy as np

#3a)
#First Solution
#Created the matrix myself then turned it into numpy matrix
num = 0
Brick = []
for x in range (0,3):
    Brick.append([])
    for y in range (0,4):
        Brick[x].append([])
        for z in range (0,5):
            Brick[x][y].append([])
            Brick[x][y][z] = num
            num = num+1
mBrick = np.array(Brick)            
print(Brick)
print()
print(mBrick)
print()
print("Shape is",mBrick.shape)
#mBrick is a 3D matrix containing the values from 0-59

[[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14], [15, 16, 17, 18, 19]], [[20, 21, 22, 23, 24], [25, 26, 27, 28, 29], [30, 31, 32, 33, 34], [35, 36, 37, 38, 39]], [[40, 41, 42, 43, 44], [45, 46, 47, 48, 49], [50, 51, 52, 53, 54], [55, 56, 57, 58, 59]]]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]]

 [[40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]]]

Shape is (3, 4, 5)


In [82]:
#3a)
#Second Solution, I figured there was an easier way to construct the matrix with numpy
#Then I looked through the lectures and remembered np.empty()
#This solution uses that function and allows the matrix to be vary in dimensions
test = np.empty([3,4,5])
num1 = 0
for x in range (0,len(test)):
    for y in range (0,len(test[x])):
        for z in range (0,len(test[x][y])):
            test[x][y][z] = num1
            num1 = num1+1

print(test.shape)
print()
print(test)

(3, 4, 5)

[[[ 0.  1.  2.  3.  4.]
  [ 5.  6.  7.  8.  9.]
  [10. 11. 12. 13. 14.]
  [15. 16. 17. 18. 19.]]

 [[20. 21. 22. 23. 24.]
  [25. 26. 27. 28. 29.]
  [30. 31. 32. 33. 34.]
  [35. 36. 37. 38. 39.]]

 [[40. 41. 42. 43. 44.]
  [45. 46. 47. 48. 49.]
  [50. 51. 52. 53. 54.]
  [55. 56. 57. 58. 59.]]]


In [97]:
#3b)
#This creates a test array
testList = np.array([])

for x in range(0,10):
    testList = np.append(x,testList)
print(testList)

#Gives array of only even numbers
testList = testList[testList%2==0]
print(testList)

[9. 8. 7. 6. 5. 4. 3. 2. 1. 0.]
[8. 6. 4. 2. 0.]


In [129]:
#3c)
#populates the matrix
tMatrix = np.empty([5,5])
for x in range(0,len(tMatrix)):
    for y in range(0,len(tMatrix[x])):
        tMatrix[x][y] = int(np.random.randint(100))
        
print(tMatrix)

#tMatrix.sort()

#Creates array to hold maximums
maxs = np.array([])
for x in range(0,len(tMatrix)):
    maxs = np.append(0, maxs)

cmax = tMatrix[0][0]

for x in range(0,len(tMatrix)):
    cmax = np.amax(tMatrix[x])
    maxs[x] = cmax
print()
print(maxs)

#maxs is an array of all the highest values from each row

[[33. 62. 95. 86. 35.]
 [ 4. 46.  9. 35. 40.]
 [ 4. 93. 52. 17. 33.]
 [ 6.  9. 30. 32. 94.]
 [29. 58. 88. 33. 65.]]

[95. 46. 93. 94. 88.]


In [ ]:
#4a)
#arr[1:, :2]

#4b)
#arr[1, 1:]