In [76]:
import numpy as np
import pandas as pd

#Question 1 function
def makeBinMat(rsize,csize):
    matrix = np.ones([rsize,csize],dtype=int)
    #i=row
    for i in range(len(matrix)):
        #j=column
        for j in range(len(matrix[i])):
            if (i+j) % 2 == 0:
                matrix[i][j]=0; 
    return matrix

#Makes call to Q1 function and prints answer
print(makeBinMat(8,8))

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [93]:
#Question 2

#2a)
#Creates Global matrix to use
Gmatrix = np.random.randn(6, 4)

#Gets 12th biggest element of matrix
#takes any matrix of at least 12 elements
def get12(matrix):
    
    if (len(matrix)*len(matrix[0]))<12:
        print("Error: Matrix not large enough")
        return
    np.sort(matrix)
    tracked = []
    for i in range(len(matrix)):
        for j in range(len(matrix[i])):
            tracked.append(matrix[i][j])
    tracked.sort()
    return tracked[(len(tracked)-12)]

#Prints answer to Question 2a)
print(get12(Gmatrix))
print()

#2b)

def makeTable(matrix):

    mean = matrix.mean(axis=0)
    std = matrix.std(axis=0)
    small = matrix.min(axis=0)
    sf = np.percentile(matrix,75,axis=0)
    big = matrix.max(axis=0)
    holder = np.array([mean, std, small, sf, big])
    #holder = {"mean":mean, "std":std, "min":small, "75%":sf, "max":big}
    df = pd.DataFrame(holder, index = ["mean", "std", "min", "75%", "max"])
    print(df)
    
#Prints answer to 2b)    
makeTable(Gmatrix)

-0.29385210811481394

             0         1         2         3
mean  0.116567 -0.357364 -0.331031 -0.485536
std   0.609238  0.814911  0.654504  1.389615
min  -0.699554 -1.381330 -1.254829 -2.011619
75%   0.729081  0.081469  0.264343 -0.104879
max   0.869983  0.914398  0.552460  2.173560
